config {
    type: "incremental",
    schema: "PRODUCTION",
    name: "DIM_TB_LINHA",
    tags: ["PRODUCTION"],
    uniqueKey: ["ID_LINHA"],
    description: "Indica as linhas do grupo boticário.",
    columns: {
        ID_LINHA: "Código único da linha",
        DES_LINHA: "Descrição da linha"
    }
}

SELECT
  ID_LINHA,
  DES_LINHA

FROM ${ref("caseboticario-456516", "STAGING", "STG_TB_LINHA")}